### ISSUE TITLE
Dropping Python 2.7 support

### ISSUE THREAD

**Issue by wesm** [pandas-dev/pandas2#5]
There were a few comments about this in the initial pull requests. 

Some of my arguments for dropping Python 2.7 support
- Probably first production-ready release of pandas 2.x will realistically be late 2017 / early 2018 (beta / testing releases available before then). This means < 3 years until Python 2 end-of-life (https://pythonclock.org/)
- C++11 is not well supported in Windows builds of Python 2.7 due to a dependence on an older MSVC runtime. I feel pretty strongly that judicious use of modern C++ (aka C++11/14) will yield better developer productivity (`auto`, anyone?) and higher quality software in the libpandas internals
- Can start thinking about / making use of Python 3.x only features, like asyncio

It would be great for us to reach some decision about this and also join the Python 3 statement: https://python3statement.github.io/ (per @takluyver suggestion)

**Comment by shoyer** [comment]
I'm totally on board with this for pandas 2.0.

**Comment by jorisvandenbossche** [comment]
Me as well, +1

**Comment by sinhrks** [comment]
+1

**Comment by wesm** [comment]
Anyone opposed to joining the Python 3 statement website? I'll leave the question open for a few days before we decide one way or another

**Comment by jorisvandenbossche** [comment]
With the thumbs up I mean that I am **not** opposed :)

**Comment by TomAugspurger** [comment]
👍 Like IPython's timeline that's split between IPython 5.x LTS and other, we should note that pandas 1.x will support 2.7 until sometime (2020?), and 2.x is py3 only.

**Comment by FrancescAlted** [comment]
+1 for dropping support for Python 3 on pandas 2.0

**Comment by jtratner** [comment]
Sounds like the right choice to go python 3 only for 2.X

**Comment by takluyver** [comment]
There seems to be pretty enthusiastic support for the general idea. Would you like me to add pandas to the [Python 3 statement website](https://python3statement.github.io/)?

Also, is there a square-ish version of the [pandas logo](https://github.com/pydata/pandas/blob/master/doc/logo/pandas_logo.png) somewhere? Or is it OK if I cut out just the three plots on the right and put them above the word **pandas**?

**Comment by TomAugspurger** [comment]
+1 to joining the Python 3 statement, but do we have a rough date for when pandas 1.X support would end? Not that this is binding...

**Comment by wesm** [comment]
@takluyver that is fine by me if there are no objections from others. 

If/when pandas 2.0 goes to production, we'll have to decide how much longer to continue maintaining 1.x (e.g. what severity of bug fix will merit backporting / bugfix release). Hard to predict until we get there

**Comment by takluyver** [comment]
Have a look at python3statement/python3statement.github.io#49, which adds it using the right-hand part of the logo.

The statement is roughly saying that our projects won't make any more Python 2 compatible releases beyond 2020. We won't enforce that, of course, but I think dropping support in four years time should be reasonable.

**Comment by jorisvandenbossche** [comment]
@takluyver That looks good to me, thanks. 
I see that not all projects with a logo are listed in the timeline, so I suppose we can always later add it there when we have an idea of the timeline of 1.x and 2.x?

**Comment by takluyver** [comment]
Yep, the timeline is an optional extra - there's no need to have a detailed schedule worked out to sign the statement. :-)

**Comment by takluyver** [comment]
I'll merge the PR adding pandas to the python3statement website tomorrow unless anyone objects.

**Comment by takluyver** [comment]
I've merged the PR, so pandas is on the list at https://python3statement.github.io/ . Thanks everyone :-)

**Comment by hugovk** [comment]
Pandas is now Python 3.6+ (and next release 3.7+ https://github.com/pandas-dev/pandas/pull/41989).

Safe to close this issue now? :)
