### ISSUE TITLE
Design Doc ipython is broken

### ISSUE THREAD

**Issue by jbrockmendel** [pandas-dev/pandas2#72]
https://pandas-dev.github.io/pandas2/internal-architecture.html

ipython blocks are showing e.g.

```
In [9]: s = pd.Series([True, False, True])
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-9-9b974089dc19> in <module>()
----> 1 s = pd.Series([True, False, True])

NameError: name 'pd' is not defined
```

The "this exposition" link on the [strings](https://pandas-dev.github.io/pandas2/strings.html) page now leads to a popup that tries to install Flash.

**Comment by gfyoung** [comment]
That's awkward...PR is welcome to patch!

**Comment by iskandr** [comment]
Just noticed this too but would have no idea how to fix it.

**Comment by wesm** [comment]
I will see if I can fix it today. The design docs were written almost 2 years ago, so need to be updated at some point as we've had a chance to think about requirements some more

**Comment by wesm** [comment]
Fixed
